### ISSUE TITLE
Chart component with View trends and view stats

### ISSUE THREAD

**Issue by qisforq** [AthletiFi/athletifi-website#103]
### Objective
Create a dynamic 'Chart' component that initially displays loading bars and transforms into a line graph when user clicks `View trends`.

### Tasks

1. **Recharts Integration**
   - [x] Integrate the Recharts library to create the chart component in a new file (e.g.`components/Chart.jsx`)
   - [x] Customize the chart to fit the design requirements of the dashboard mockup.
   - [x] Ensure the component is responsive and adapts to various screen sizes.

2. **Loading State Visualization** (optional)
   - [ ] Implement loading bars as the initial state of the chart to indicate that data is being fetched.

3. **Dynamic Transformation**
   - [ ] Write the logic to transform the loading bars into a line graph when the 'View trends' button is clicked.
   - [ ] Ensure the transformation is smooth and visually appealing.

4. **Data Binding**
   - [ ] Connect the chart component to the API Gateway (using Axios) to fetch the required stats data.
   - [ ] Ensure the line graph accurately represents the stats data over time.

#### Desktop View:
<img src="https://github.com/AthletiFi/athletifi-website/assets/33239211/1afedb28-4069-4ec0-b14a-1f1114f0309e" width="500">

##### Desktop Trend Chart:
<img src="https://github.com/AthletiFi/athletifi-website/assets/33239211/7b336008-e727-4106-b9cf-21ac4a983de6" width="400">

#### Mobile View
<img src="https://github.com/AthletiFi/athletifi-website/assets/33239211/66305202-79bd-4b47-9d27-77b518800ffd" width="500">

**Comment by chef-louis** [comment]
Desktop layout created

![Image](https://github.com/AthletiFi/athletifi-website/assets/140190642/db3d81ca-9ef0-44b0-8085-6e8c34f8c1a3)

![Image](https://github.com/AthletiFi/athletifi-website/assets/140190642/4dcfd617-e92c-4f18-8327-feef8e6269da)

**Comment by chef-louis** [comment]
Needs mobile edits and responsiveness

**Comment by chef-louis** [comment]
Added mobile and tablet layouts

Mobile:
![Image](https://github.com/AthletiFi/athletifi-website/assets/140190642/b25a8e6f-7f38-476f-b84e-35f7d861d18b)
![Image](https://github.com/AthletiFi/athletifi-website/assets/140190642/eac1e1ea-e607-4105-89db-64178a696a60)

Tablet:
![Image](https://github.com/AthletiFi/athletifi-website/assets/140190642/0a0ae890-7895-43f8-b5d8-57998e941e88)
![Image](https://github.com/AthletiFi/athletifi-website/assets/140190642/ea2ec496-650c-4da7-8843-cd6934d8bcaa)

**Comment by chef-louis** [comment]
Synced up with Paula on the current iteration of chart layout/design. As a result of that discussion, I've added hover and click effects to the bar chart as well.
