### ISSUE TITLE
Create Profile component

### ISSUE THREAD

**Issue by qisforq** [AthletiFi/athletifi-website#104]
<img src="https://github.com/AthletiFi/athletifi-website/assets/33239211/41fe51c5-4471-417b-a084-40f8d04d5cdc" width="500">

#### Objective
Create the 'Profile' component that showcases player details such as Age, Club, League, Team Name, Age Group, Gender, Coach, and Bio.

#### Tasks

1. **Component Design**
   - [ ] Create the profile component in a new file (e.g.`components/Profile.jsx`).
   - [ ] Design the component using Tailwind CSS to match the dashboard mockup design.
   - [ ] Ensure the component is responsive and adapts to various screen sizes.

2. **API Integration**
   - [ ] Implement the logic to handle fetching player details (this can be done by setting up an API route (e.g. `pages/api/player-profile.js`) using Next.js API routes.)
   - [ ]  Connect to the AWS API Gateway to retrieve the latest game data, using Axios.
   - [ ] Ensure the AWS Lambda function correctly fetches the latest game data from the RDS PostgreSQL database.

3. **Data Display**
   - [ ] Integrate the data into the component using React state and props to dynamically display player information in the component.
   - [ ] Display dynamic data for age, club, league, etc.
