### ISSUE TITLE
Layout for Latest game, Charts, and profile components

### ISSUE THREAD

**Issue by qisforq** [AthletiFi/athletifi-website#105]
### Objective
Finalize the layout for the components for `Latest game` (#102), `Charts` (#103), and `Profile` (#104) sections of the dashboard

### Tasks

1. **UI Component Creation**
   - [x] Scaffold the components: `LatestGame`, `Charts`, and `Profile`.
   - [x] Define the basic shape and position for each component.

2. **Styling with Tailwind CSS**
   - [x] Apply Tailwind CSS classes to the components to match the dashboard mockup.
   - [x] Ensure responsive design for the components to accommodate various screen sizes.

#### Desktop View:
<img src="https://github.com/AthletiFi/athletifi-website/assets/33239211/e43ed16e-df5c-40b8-8266-46d121fc7fbc" width="500">

#### Mobile View
<img src="https://github.com/AthletiFi/athletifi-website/assets/33239211/8321f37a-d453-476f-86bb-f5349c4f6ac2" width="200">
