### ISSUE TITLE
Layout for Season Highlights and Top Action Reels components

### ISSUE THREAD

**Issue by qisforq** [AthletiFi/athletifi-website#107]
### Objective
Finalize the layout for the components for `Season Highlights` (#108) and `Top Action Reels` (#111) sections of the dashboard

### Tasks

1. **UI Component Creation**
   - [ ] Scaffold the components: `Season Highlights`, and `Top Action Reels`.
   - [ ] Define the basic shape and position for each component.

2. **Styling with Tailwind CSS**
   - [ ] Apply Tailwind CSS classes to the components to match the dashboard mockup.
   - [ ] Ensure responsive design for the components to accommodate various screen sizes.

#### Desktop View:
<img src="https://github.com/AthletiFi/athletifi-website/assets/33239211/0d992ffb-6509-4cf9-9958-08bbcc95510c" width="600">

#### Mobile View
<img src="https://github.com/AthletiFi/athletifi-website/assets/33239211/3b6c8c20-f460-4e2d-afed-72291891d863" width="220">
