### ISSUE TITLE
Create Season Highlights component

### ISSUE THREAD

**Issue by qisforq** [AthletiFi/athletifi-website#108]
### Objective
Develop the 'Season Highlights' component in the AthletiFi dashboard using Next.js and Tailwind CSS.

### Tasks
1. **Component Structure**
   - [x] Create the 'Season Highlights'  component in a new file (e.g.`components/SeasonHighlights.jsx`).
   - [x] Design the component using Tailwind CSS to match the dashboard mockup design.
   - [x] Ensure the component is responsive and adapts to various screen sizes.

2. **Database Schema Modification**
   - [ ] Alter the `players_team_info` table to include a new column `season_highlights` of type TEXT.

3. **Data Handling**
   - [ ] Implement the data fetching logic (this can be done by setting up an API route (e.g. `pages/api/season-highlights.js`) using Next.js API routes.)
   - [ ] Connect to the AWS API Gateway to retrieve the season highlights data, using Axios.
   - [ ] Ensure the AWS Lambda function correctly fetches the latest match data from the RDS PostgreSQL database.

#### Desktop View:
<img src="https://github.com/AthletiFi/athletifi-website/assets/33239211/7ee09ed1-794d-44c6-a933-53465b28b89c" width="600">

#### Mobile View
<img src="https://github.com/AthletiFi/athletifi-website/assets/33239211/404e4de0-afd2-4c89-b930-abffdd1fb276" width="220">
