### ISSUE TITLE
AI text generation for season highlights and match summary

### ISSUE THREAD

**Issue by qisforq** [AthletiFi/athletifi-website#109]
#### Objective
Develop the back-end logic for generating, storing, and serving the "Season Highlights"(#108) text and the "Match Summary" text (#112) using Amazon Bedrock and update the database schema accordingly.

#### Tasks

1. **Amazon Bedrock Integration**
   - [ ] Set up the integration with Amazon Bedrock to generate the season highlights text after each game.
   - [ ] Ensure that the generated text adheres to the requirement of being under three paragraphs.

2. **Data Storage Logic**
   - [ ] Implement a mechanism to store the generated season highlights text in the `season_highlights` column for the respective player.
   - [ ] Implement a mechanism to store the generated match summery text in the `match_summary` column for the respective match in the `match_results` table.
   - [ ] Create a scheduled job or trigger that invokes the Bedrock process and updates the database after each match.

3. **API Development**
   - [ ] Create a new RESTful API endpoint (e.g. `/api/season-highlights/{playerId}`) to serve the season highlights text.
   - [ ] Create a new RESTful API endpoint to serve the match summary text (can probably be combined with other needed info for the 'Match Summary' window)
   - [ ] Modify the AWS Lambda function to query the RDS database to:
       - retrieve the season highlights for a given player.
       - retrieve the summary for a given match
   - [ ] Write the SQL query within the Lambda function to select the `season_highlights` text from the `players_team_info` table.
   - [ ] Write the SQL query within the Lambda function to select the `match_summary` text from the `match_results` table.

**Comment by qisforq** [comment]
I need to get some example data from the sports tagger

**Comment by qisforq** [comment]
![Image](https://github.com/AthletiFi/athletifi-website/assets/33239211/6e7d62d7-04cb-4153-8e72-c698358be801)

**Comment by chef-louis** [comment]
Closing this task as duplicated by #233 and #232
