### ISSUE TITLE
Create Top Action Reels component

### ISSUE THREAD

**Issue by qisforq** [AthletiFi/athletifi-website#111]
### Objective
Develop the 'Top Action Reels' component in the AthletiFi dashboard using Next.js and Tailwind CSS.

### Tasks
1. **Component Structure**
   - [x] Create the 'Season Highlights' component in a new file (e.g.`components/ActionReels.jsx`).
   - [x] Design the component using Tailwind CSS to match the dashboard mockup design.
   - [ ] Ensure the component is responsive and adapts to various screen sizes.

2. **Display Thumbnails**
   - [ ] For each video highlight, dynamically create a thumbnail within the component.
   - [ ] Use the `clip_description` from the fetched data as the title for each thumbnail.
   - [ ] Style the thumbnails using Tailwind CSS to ensure they are visually appealing and match the overall design of the dashboard.

3. **Video Player Modal**
   - [ ] Integrate the `next-video` module or an alternative video player suitable for Next.js applications.
   - [ ] Configure an `onClick` event for each thumbnail that triggers a modal. This modal should contain the video player.
   - [ ] The video player within the modal should load and play the specific highlight clip selected by the user. Utilize the `video_url` alongside the `start_timestamp` and `duration` to play the exact segment of the full match recording.

4. **Data Handling**
   - [ ] Implement the data fetching logic. This can be done by setting up an API route (e.g., `pages/api/video-highlights.js`) using Next.js API routes.
   - [ ] Connect to the AWS API Gateway to retrieve the season highlights data, using Axios.
   - [ ] Ensure the AWS Lambda function correctly fetches the latest game data from the RDS PostgreSQL database.

#### Desktop View:
<img src="https://github.com/AthletiFi/athletifi-website/assets/33239211/0fa0bcd5-4fd0-45e9-bc49-7d791c27657e" width="600">

#### Mobile View
<img src="https://github.com/AthletiFi/athletifi-website/assets/33239211/572a9074-8993-4bfc-8c3b-ecc9f318c704" width="220">
