### ISSUE TITLE
Create Past matches and Match summary components

### ISSUE THREAD

**Issue by qisforq** [AthletiFi/athletifi-website#112]
### Objective
Develop the 'Past matches' component, which displays a list of the matches that player has played in, displaying the teams, score, date, and a `summary` button to view the 'Match Summary' Window.

### Tasks

1. **Past Matches Component Layout**
   - [x] Create the 'Past Matches' component in a new file (e.g., `components/PastMatches.jsx`).
       - 'Past matches' should show a list of matches, each list item showing the club logos for both teams, the score, the names of the teams, the date, and the `summary` button
summary of the match, 
   - [x] Design the component using Tailwind CSS to match the dashboard mockup design.
   - [x] Ensure the component is responsive and adapts to various screen sizes.

2. **Match Summary Component Layout**
   - [x] Create the 'Match summary' component (either in the same file or a new file)
       - 'Match summary' should show all the info shown in the 'past matches' list item and the location info, weather info, summary text
       - Display the list of highlight videos from that game, including their description.
 
3. **Data Fetching**
   - [ ] Implement the data fetching logic (this can be done by setting up an API route (e.g. `pages/api/past-matches.js`) using Next.js API routes.)
   - [ ] Connect to the AWS API Gateway to retrieve the latest match data, using Axios.
   - [ ] Ensure the AWS Lambda function correctly fetches the latest match data from the RDS PostgreSQL database.
   - [ ] Integrate the data into the 'Latest Match' component using React state management.

### Desktop View:
**Past Matches component:**
<img src="https://github.com/AthletiFi/athletifi-website/assets/33239211/e79d32b9-c8a0-4a3a-bc16-2daaa867a12a" width="600">

**Match Summary component:**
<img src="https://github.com/AthletiFi/athletifi-website/assets/33239211/519f89cb-958d-4255-b222-8c2888bad217" width="500">

### Mobile View
**Past Matches component:**
<img src="https://github.com/AthletiFi/athletifi-website/assets/33239211/d1b0f746-728f-4592-97ee-b6682778dce6" width="300">

**Match Summary component:**
<img src="https://github.com/AthletiFi/athletifi-website/assets/33239211/5db8fe45-b8a1-4106-a4cc-47493045af56" width="300">

**Comment by pm-moyanor** [comment]
working in my forked repo "paula-pastMatches" branch
