### ISSUE TITLE
Create Teammates component

### ISSUE THREAD

**Issue by qisforq** [AthletiFi/athletifi-website#113]
#### Objective
Create the 'Teammates' component that showcases the other players on the team, including their avatar, name and player number.

> **_NOTE:_**  The teammates should _not_ be clickable/linked to the profiles for the respective players at this time.

#### Tasks

1. **Component Design**
   - [x] Create the 'Teammates' component in a new file (e.g.`components/Teammates.jsx`).
   - [x] Design the component using Tailwind CSS to match the dashboard mockup design.
   - [x] Ensure the component is responsive and adapts to various screen sizes.

2. **API Integration**
   - [ ] Implement the logic to handle fetching teammate (player) details - this can be done by setting up an API route using Next.js API routes.
       - Note: Check to see if another API route (such as for player profile) can be reused here
   - [ ] Ensure the AWS Lambda function correctly fetches the data needed from the RDS PostgreSQL database.

3. **Data Display**
   - [ ] Integrate the data into the component using React state and props to dynamically display teammate information in the component.
   - [ ] Display dynamic data for teammate name, player number, avatar

#### Desktop View:
<img src="https://github.com/AthletiFi/athletifi-website/assets/33239211/23446315-8ab5-494e-a8ad-2b1b44cc94d5">

#### Mobile View
<img src="https://github.com/AthletiFi/athletifi-website/assets/33239211/3203451b-925f-4920-ae65-1d105a272652" width="250">
