### ISSUE TITLE
Layout for Past matches & Teammates components

### ISSUE THREAD

**Issue by qisforq** [AthletiFi/athletifi-website#114]
### Objective
Finalize the layout for the components for `Past matches` (#112) and `Teammates` (#113) sections of the dashboard

### Tasks

1. **UI Component Creation**
   - [x] Scaffold the components: `Past matches` and `Teammates`.
   - [x] Define the basic shape and position for each component.

2. **Styling with Tailwind CSS**
   - [x] Apply Tailwind CSS classes to the components to match the dashboard mockup.
   - [x] Ensure responsive design for the components to accommodate various screen sizes.

#### Desktop View:
<img src="https://github.com/AthletiFi/athletifi-website/assets/33239211/fba194f2-3ff4-40d7-b0e0-7b1d0e475196" width="600">

#### Mobile View
<img src="https://github.com/AthletiFi/athletifi-website/assets/33239211/bd13b262-5288-437f-8247-d8ee4ff0e88c" width="250">
