### ISSUE TITLE
Consolidate API endpoints and corresponding Lambda functions

### ISSUE THREAD

**Issue by qisforq** [AthletiFi/athletifi-website#162]
### Objective:
Combine the logic of the multiple Lambda functions for each of the API endpoints into a single function to reduce the number of API calls made by the dashboard.

#### Tasks:

- [x]  Identify the common data requirements of the dashboard components that currently make separate API calls.
- [x] Design a new consolidated API endpoint (e.g., `/api/dashboard/{player_id}`) to fetch all the necessary data in a single request.
- [x]  Create a new Lambda function to handle the consolidated API endpoint.
- [x] Write optimized SQL queries to fetch the required data from the RDS database tables (`match_results`, `player_ratings`,`player_profile`, etc.).
- [x] Refactor the dashboard components to make a single API call to the consolidated endpoint and update the respective sections with the received data.

**Comment by chef-louis** [comment]
@HectorAgudelo I've consolidated the 5 API calls into 1 lambda function (getDashboardData under AWS Lambda). The result does look a bit different so we will want to update the front-end handling which we can do together. Let me know when you have time to look into this.

**Comment by qisforq** [comment]
@chef-louis minor suggestion: for the `player_ratings`, it seems we can take `src_ref` and `name` out of each of the rating objects, since all the ratings returned will be for the same player
