### ISSUE TITLE
Create 'Settings' Page

### ISSUE THREAD

**Issue by qisforq** [AthletiFi/athletifi-website#177]
### Objective:
Develop the Settings page, including sections for Account Details, Notifications, and Manage Referrals.

#### Tasks:

 - [x] Create a new component or page for the Settings page.
 - [x] Implement the Account Details section, allowing users to change their email, password, or delete their account. Use dummy functionality for now until User Login is complete (#170)
 - [x] Implement the Notifications section, enabling users to manage their notification preferences. Use dummy functionality for now until User Login is complete (#170)
 - [x] Implement the Manage Referrals section, displaying referral information and any relevant actions. Use dummy functionality for now until the Referral feature is complete. (#176)
 - [x] Link the Settings page to the side menu (#175).

**Comment by chef-louis** [comment]
Remaining TODOs:
* Add ability to edit username and password
* Add ability to add referrals
