### ISSUE TITLE
Create 'Help & Support' page

### ISSUE THREAD

**Issue by qisforq** [AthletiFi/athletifi-website#179]
### Objective:
Develop the Help & Support page, including sections for reporting a problem, FAQ, contact options, and view terms and policies.

#### Tasks:

 - [x] Create a new component or page for the Help & Support page.
 - [x] Implement the "Report a Problem" section, using an email link as the mechanism for users to submit issues or feedback.
 - [x] Implement the FAQ section, displaying a list of frequently asked questions and their answers (provided by #178). Provide an expandable/collapsible view for each FAQ item to show the answer when clicked.
 - [x]  Implement the "Send an Email" and "Chat with Us" buttons, linking them both to email links.
 - [x]  Implement the "Terms and Conditions" and "Privacy Policy" buttons, linking them to the respective legal pages.
 - [x]  Link the Help & Support page to the side menu (#175).

**Comment by chef-louis** [comment]
@pm-moyanor checkout the settings page and components that was recently merged into dev. Before you start on the Help & Support page, let me know if you wanted to touch base, there may be some refactoring I could do to make this part a bit easier / more consistent.
