### ISSUE TITLE
Update Notifications Feature

### ISSUE THREAD

**Issue by qisforq** [AthletiFi/athletifi-website#180]
### Objective:
Enhance the Notifications section of the Settings page to allow users to manage their notification preferences effectively.

### Tasks:

 - [x] Research and evaluate different approaches for managing user notification settings, such as using a tagging system similar to Uber (@chef-louis's idea)
 - [x] Design a scalable and flexible data model for storing user notification preferences.
 - [x] Implement the backend API endpoints to retrieve and update user notification settings.
 - [x] Update the Notifications section of the Settings page to display the available notification categories and options (related to #177 )
 - [x] Implement toggle switches or checkboxes for each notification category, allowing users to enable or disable specific types of notifications.
 - [x] Ensure that the selected notification preferences are saved and persisted correctly when the user updates their settings.
 - [x] Test the notification settings functionality to verify that the preferences are accurately stored and applied.
 - [x] Consider implementing default notification settings for new users and provide options to customize them during the onboarding process.
 - [ ] Evaluate the performance and scalability of the notification settings system, especially for a large number of users and notification categories.

**Comment by chef-louis** [comment]
Doing some research indicates that having an individual table for users and another for notification preferences, we can then create a many-to-many relationship table between them to house preferences for the various combinations. This seems to be both a performant and scalable approach as we grow the communications channels.

I'll get the relevant tables added

**Comment by qisforq** [comment]
Nice work on this @chef-louis, the new design approach sounds very intuitive and performant. Looking forward to seeing the tables!

**Comment by chef-louis** [comment]
* Added lambda function to access notification preferences and render settings appropriately on the front-end
* TODO: add update functionality to POST / update changes in front-end to the backend

**Comment by chef-louis** [comment]
Functionality of adding / removing notification preferences for users is completed.

TODO for further optimization:
* Refactor User state to leverage Jotai
* Test scalability
* Implement default notifications / prompt user on sign-up

**Comment by chef-louis** [comment]
Credit to Paula for a great idea on how to initialize notification settings and prompt users to modify if desired. Details on the flow below:

1. Add the following notifications as enabled on default:
* AthletiFi Updates
* General Highlights
* My Player Cards

2. On welcome email to user, communicate the default settings for notifications and share a link to the settings page for updating preferences as desired.
