### ISSUE TITLE
Refactor Mux Video Optimization as Lambda Function

### ISSUE THREAD

**Issue by qisforq** [AthletiFi/athletifi-website#194]
### Objective:
Refactor the Mux video optimization process to use a Lambda function that optimizes videos upon uploading to an S3 bucket, instead of optimizing during the Next.js project build.

### Tasks:

- [x]  Create the Lambda function to be triggered whenever a new video file is uploaded to the videos S3 bucket.
- [x] Install the necessary dependencies and libraries in the Lambda function to interact with the Mux API (e.g., @mux/mux-node for Node.js).
- [x]  Retrieve the uploaded video file details from the S3 event trigger.
- [x] Create a new Mux asset using the Mux API (see [API doc](https://docs.mux.com/api-reference#video/operation/create-asset) for more info)
- [x] Wait for the Mux asset to be processed and optimized, then retrieve the optimized video playback URL (HLS URL) from the Mux asset.
- [x] Store the optimized video details (e.g., playback URL, asset ID) in a database or cache for later use.
- [x] Update the Next.js application to fetch the optimized video details from the database or cache when needed, instead of relying on the build-time optimization.
- [ ] Modify the video player component in the Next.js application to use the retrieved optimized video playback URL (HLS URL) for streaming.
- [ ] Deploy the Lambda function to AWS and ensure that it is properly triggered when new videos are uploaded to the S3 bucket.
- [ ] Update the video upload process in the Next.js application to upload videos directly to the S3 bucket instead of triggering optimization during the build process.

**Comment by qisforq** [comment]
https://docs.mux.com/core/make-api-requests#using-mux-with-serverless-functions

**Comment by qisforq** [comment]
Here is my simplified, un-chatgptified, understanding of the approach:

1. a video gets uploaded to S3, triggering this lambda function
2. The lambda function takes the S3 URL of the video and sends it to Mux using the 'Create Asset' [API method](https://docs.mux.com/api-reference#video/operation/create-asset)
3. Mux returns an asset id (or you have to query for the asset id after the video is finished optimizing)
4. We need to save that asset id in the database, so we can then use it to call the video in the next-video player

**Comment by chef-louis** [comment]
* Successfully able to run Create via mux video API in a local nodejs project
* Lambda function is running into a timeout issue when running the same create asset API call
* Tried increasing time and resources but still times out
* The external API call to mux may be slow/timing out. Continuing to look into more ways of debugging but will get more thoughts from the group in standup today.
