### ISSUE TITLE
Prepare dashboard for demo deployment

### ISSUE THREAD

**Issue by qisforq** [AthletiFi/athletifi-website#200]
### Objective:
We would like to prepare the dashboard for demo presentation to stakeholders, which includes the potential users (summer select parents), coaches, club directors, and potential investors. 

In order to demo the full user experience, including scanning the cards to go directly to the dashboard page, we need the code to be deployed directly to the athleti.fi domain. This will require opening the dashboard to public access, before the user login feature is complete. To mitigate access from the general public, we should obfuscate access to the dashboard endpoints by removing links from the other pages, and research ways to limit access based perhaps on a simple password or IP restriction.

### Tasks:

- [ ] Cleanup all eslint warnings which could lead to build errors.
- [ ] Remove buttons that link to the Dashboard from other parts of the website
- [ ] Research methods to restrict public access, using IP restrictions, simple password, or another method.
