### ISSUE TITLE
Convert the "Sign Up" page into a "Contact Us" page

### ISSUE THREAD

**Issue by qisforq** [AthletiFi/athletifi-website#89]
Currently, we have a 'Sign Up' page, which is currently linked to two buttons (one titled 'Sign up' and the other titled 'Contact Us':

#### Home page with two buttons that link to sign-up page:
<img src="https://github.com/AthletiFi/athletifi-website/assets/33239211/ceea5d36-96db-47a5-b682-e25ebcb8ac95" width="500">

#### Current Sign-up page:
<img src="https://github.com/AthletiFi/athletifi-website/assets/33239211/c7368eeb-d0c1-4d70-bda2-f543dfd1eb93" width="500">

### Tasks:

- [x] Change the title of the 'Sign up' button in the Nav bar to 'Contact Us'
- [ ] Add a 'Contact Us' button in the footer (coordinate with Hector who is working on a [new footer](https://github.com/AthletiFi/athletifi-website/issues/88))
- [x] Change the title of the Sign Up page to reflect that it is a 'Contact Us' page
    - [x] Change "Start Your Digital Soccer Card Collection Journey" to `Connect with the AthletiFi team`
    - [x] Change "Sign-up for exclusive updates! Become part of the sport's revolution" to `Get in Touch!`
    - [x] Change "By subscribing, you're not only embracing the future of sports..." to `As we gear up for the launch of our groundbreaking platform, we're eager to connect with those who share our passion for revolutionizing youth soccer. If you're interested in learning more about our products, exploring opportunities for collaboration, or contributing to our journey, we'd love to hear from you.`
- [x] Expand the fields of the 'Contact Form' to include:
    - Name
    - Email
    - Message
- [x] Update the 'Join-Newsletter' Collection in the [AthletiFi Website CMS](https://github.com/AthletiFi/athletifi-website-cms) to accept the Name and Message fields.
    - [x] (optional) rename the 'Join-Newsletter' Collection to something more appropriate (contact-us-message?)

**Comment by chef-louis** [comment]
- Included some basic form validation on the message length (max of 1000 characters).
- Note: may want to include further limitations on contact submissions (ie. max number of submissions allowed per email in 24 hr window)

**Comment by chef-louis** [comment]
Went ahead with creating a new collection called `contact-us-message`. Currently the collection for `join-newsletter` still exists.

**Comment by chef-louis** [comment]
Tested the POST request successfully interacts with the backend on a contact submission.
Note: Another potential add could be to email the contact submission to the user's email for transparency/log of record.

**Comment by chef-louis** [comment]
@HectorAgudelo Let me know when you start working on the Footer updates. I can make the edits to include the Contact Us button. Thanks.
