### ISSUE TITLE
Create Hero/Banner Section of Dashboard

### ISSUE THREAD

**Issue by qisforq** [AthletiFi/athletifi-website#99]
### Objective
Develop a hero/banner section for the dashboard that showcases the club logo, player name, club name, team name, and card image.

### Tasks
1. **Frontend Component Creation**
   - [ ] Create a new component in the `components/dashboard` directory.

2. **Data Integration**
   - [ ] Set up state management to handle the dynamic insertion of the player's name, club name, and team name.
   - [ ] Implement a mechanism to fetch and display the correct club logo and player trading card image.

3. **Styling**
   - [ ] Design the layout according to the mockup with attention to alignment, spacing, and typography.
   - [ ] Use Tailwind CSS classes to style the hero/banner section as per the design mockup.
   - [ ] Ensure responsive design by using Tailwind's responsive prefix (`sm:`, `md:`, `lg:`, `xl:`) where necessary.
   - [ ] Utilize CSS Grid or Flexbox to arrange the elements as per the design specification.

4. **Image Optimization**
   - [ ] Use Next.js Image component for optimized image loading.
   - [ ] Ensure that the trading card image is responsive and has a placeholder while loading.

#### Desktop View:
<img src="https://github.com/AthletiFi/athletifi-website/assets/33239211/17dfb258-28e9-4890-a3ab-b085b6c2cf4b">

#### Mobile View
<img src="https://github.com/AthletiFi/athletifi-website/assets/33239211/09821a6d-1130-443b-97f7-55a2dd23f49a" width="300">
